source 'http://rubygems.org'

gem 'rails', '3.0.7'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'sqlite3'

#Useful for progressive enhancement
gem 'will_paginate', '3.0.pre2'

gem "haml-rails"
gem "jquery-rails"

group :development do
  gem 'faker'
  gem 'populator'
end